### ISSUE TITLE
Properly display Z-Wane config parameters.

### ISSUE THREAD

**Issue by bwosborne2** [opensmarthouse/opensmarthouse-webui#6]
Apparently the OH3 UI cannot properly display configuration parameters that have options and allow manual entry. Here is a quote from ysc.
```
The combination of type: INTEGER, limitToOptions: false and options defined is not supported by the config parameter control at the moment.
```

Please insure we properly support this.

Source:
https://community.openhab.org/t/zwave-oh3-config-parameters/119789/22

**Comment by cdjackson** [comment]
This needs to be resolved in openhab - it prevents ZWave being used. This is a clear use case that was agreed in ESH and is documented in openHAB - this is why we have the limit to options etc, so it's a but in openHAB - not here.
